[main]
import_ips = true 
import_prefixes = false
import_cabling = "cdp"       # Valid options are ["lldp", "cdp", "config", false]
import_intf_status = false     # If set as False, interface status will be ignore all together
import_vlans = "config"         # Valid options are ["cli", "config", true, false]
configs_directory= "configs"

[netbox]
# The information to connect to NetBox needs to be provided, either in the config file or as environment variables
address = "http://localhost:8080"                   # Alternative Env Variable : NETBOX_ADDRESS
token = "0123456789abcdef0123456789abcdef01234567"  # Alternative Env Variable : NETBOX_TOKEN
verify_ssl = false                                   # Alternative Env Variable : NETBOX_VERIFY_SSL

[network]
# To be able to pull live information from the devices, the credential information needs to be provided
# either in the configuration file or as environment variables ( & NETWORK_DEVICE_PWD)
login = "admin"      # Alternative Env Variable : NETWORK_DEVICE_LOGIN
password = "cisco"   # Alternative Env Variable : NETWORK_DEVICE_PWD

[batfish]
address= "localhost"    # Alternative Env Variable : BATFISH_ADDRESS
port_v1 = 9997
port_v2 = 9996
use_ssl = false

[logs]
# Define log level, currently the logs are printed on the screen
# level = "info" # "debug", "info", "warning"